name: Update Metadata

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: System deps for OpenCV
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests pillow opencv-python-headless

      - name: Run sanitize_md_filenames.py
        run: python sanitize_md_filenames.py

      - name: Run download_and_relink_images.py
        run: python download_and_relink_images.py all

      - name: Run jsonScript.py
        run: python jsonScript.py

      - name: Check for changes
        id: check_changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changed
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "albion@gmail.com"
          git config --local user.name "Albion Free Market"
          git add -A
          git commit -m "chore: update repository assets"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
