name: Update Metadata

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run jsonScript.py
        run: python jsonScript.py

      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code metadata.json || echo "has_changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "albionfreemarket@gmail.com"
          git config --local user.name "Albion Free Market"
          git add metadata.json
          git commit -m "Update metadata.json"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
